# Generated by Django 5.0.7 on 2024-08-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='tags',
            field=models.ManyToManyField(to='blog.tags'),
        ),
    ]
